language: android
jdk: openjdk11
env:
  - JAVA_OPTS="-XX:+IgnoreUnrecognizedVMOptions --add-modules java.xml.bind"
android:
  components:
    - tools
    - platform-tools
before_install:
  - yes | sdkmanager 'build-tools;32.0.0'
  - yes | sdkmanager 'platforms;android-32'
  - yes | sdkmanager --licenses
before_script:
  - chmod +x gradlew
script:
  - ./gradlew build check