language: android
jdk: openjdk11
android:
  components:
    - tools
    - platform-tools
before_install:
  - yes | sdkmanager --install 'build-tools;32.0.0' 'platforms;android-32'
  - yes | sdkmanager --licenses
before_script:
  - chmod +x gradlew
script:
  - ./gradlew build check