language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-32.0.0
    - android-32
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
script:
  - ./gradlew build check